[gcp_service_account]
type = "service_account"
project_id = "food-app-462903"
private_key_id = "671ca230975ae850b33c08154dc95193af7126e1"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVUr7Bin39tcSL
jECyZJQGvIOO/gMv2dDQ9q79XuJSgYElNxl6od52nMWcASyd2ToJjxCgHR+WWjNj
Ap4/FKjcUIeR/rUZjDrmo87DcoJp4jJupIfTV2p/frI5ToUXUvSl9gWYtFo4l+1I
a97xMvTZSWRfvdCeJ+Vd7jcZOPOd3f6QUETDaFQvldsVbv8zX9KrlPWLjmdkRFx9
Up/TfwfOurcfUUkED/ZntZAJyRMltgap2xBqsYcPuhVEw2cLZEcOsJRNnPXl0ssN
TVrfQVeT6l7yYrbgNY2oknyhRe78VMrIel9aZf/UD3csHfF0TOim/s4N1dbfHypF
AtFhWp1tAgMBAAECggEACVgkTHiLT82CREWawOW4eToRPjaAv7wYEks3+5fILKqJ
FG7/Mfi8tK/l1RFVGb399ZS7evQDofOmDBh9g5BdXDc31QyV9L5IhzlWMYgGz+oN
YPzaiUarPtX3Kxz2JgEnf8yQzrFZwWBgT7uP6rtbb9gv6iS3qnHfcXehmLx+qWPP
RwsJZUT2WkMI+1piaTEM/hxch+hcOFhuZiqS4rbcIMROSCOAqbOwuonCQBREzJqK
BsmOKQICa/ptYAG6yIZSRb8xU8VFQ6FAJQlsEILcKe7TWXQykEajGf7KLZEy0PuH
WU84gRkULJ/BYFXyzCG6zYrTyLHjyS3Jds2UMgaDeQKBgQD1ivhNi344OlzYDj5P
BI9kZ0RyNFGlJJysHpd80QnYptGxen1knvymVoHo+mO/fqXoHfVTuloZJi4L3u9H
1DFaWEgkVlH3JW/xfbIBDo1eqfWoJhglErEOv1oiieqML8kCUABogOQ/WCcZ4Hy/
mDXnV7hYHiZgGzn7Y+EOTo7gqQKBgQDeaIA2Jh1I8vslo1kbDX0DWoKHG1I9F3Ie
DAX49cXhLt8vpn8mE5URqy+0AUg4zMa3aI3tJmT9ggcoA1jx6gfZSdzIQLhX3moj
QtIpjhiGL6AEVVPGfEiDlLbDxte6ntuFVga4xwpG/KN0RbFeQwpTZME/j0V7FYdb
oyxrKNkdJQKBgDXs3FVjckf1AVjt399IuBkr2MtgFCI5pTLj0Q83dXsgP+NDbHCB
vijlzMgW3Xs73EHa+nr17T2itfAjeNeEkYYu50EbuAqYLTqTCVnUEVYd63aPTzQt
I7eCbNAzC9DX2cRpP32z+Oy0dnnnZF5LlmMFT9YCYRkwQY6lQ9L5i8VpAoGBAMD7
aBSUKeD8hRN5k323zHu2c4AMIuXDjE+qGxyVFah45UwRak59u2FjarcETciLVvoa
DNxz7jlSNCdyECGI8lqGjr5r+gi0guApwPYxx/HXLT/VUiXt/XW++n8R8GqMIOqn
ZJm8i5xg5uui9W5XOYR27n/aL23HlnXbNlWdUhbJAoGAZ5vD/p87CO4exF0nqvvt
TQAdEmyDRqP6cV/C89HjMbnroTYCU2iXEcW4xpfybqU26E/Xv9KwaRznylY1oHdx
gal97YykE9hIlWIjRIIrOSTs5ASCueUHJJMGtU7RSEY0zfFHprzqSiRiQgsueDcJ
4N1X2VWzEZHNEMVqT1lrTRw=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-access@food-app-462903.iam.gserviceaccount.com"
client_id = "105409192784235844642"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40food-app-462903.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
